import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bergen Fontforening",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/jrq1ohe.css" />
        <link rel="icon" href="/icon.png" sizes="any" />
      </head>
      <body className={inter.className}>
        <header>
          <div></div>
          <div>
            <Link href="/">
              <p className="link"> Hovedsiden </p>
            </Link>
            <Link href="/arkivet">
              <p className="link"> Arkivet </p>
            </Link>
            <Link href="/semesteretsfont">
              <p className="link"> Semesterets font </p>
            </Link>
            <Link href="/om">
              <p className="link"> Om oss </p>
            </Link>
          </div>
          <div className="socials">
            <a href="https://instagram.com/bergenfont">
              <Image src="/ig.svg" width={40} height={40} alt="IG"></Image>
            </a>
            <a href="https://www.linkedin.com/company/96013843">
              <Image
                src="/linkedin.svg"
                width={40}
                height={40}
                alt="LinkedIn"
              ></Image>
            </a>
          </div>
        </header>
        {children}
        <footer>
          <p style={{ fontFamily: "Computer Modern Italic" }}>
            Vi fremmer, fronter og formidler fonter!
          </p>
          <p>
            Kontakt:{" "}
            <button className="email">
              <Link href="mailto: post@bergenfont.no">post@bergenfont.no</Link>
            </button>
          </p>
        </footer>
      </body>
    </html>
  );
}
